__global__ void tsort1(int *input0,int *result0){
  unsigned int tid = threadIdx.x;
  unsigned int bid = blockIdx.x;
  extern __shared__ __attribute__ ((aligned (16))) unsigned char sbase[];
  (( int *)sbase)[tid] = ((tid&1)==0) ? min(input0[((bid*512)+tid)],input0[((bid*512)+(tid^1))]) : max(input0[((bid*512)+tid)],input0[((bid*512)+(tid^1))]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&2)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^3)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^3)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&1)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&4)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^7)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^7)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&2)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&1)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&8)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^15)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^15)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&4)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&2)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&1)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&16)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^31)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^31)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&8)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&4)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&2)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&1)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&32)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^63)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^63)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&16)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^16)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^16)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&8)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&4)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&2)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&1)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&64)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^127)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^127)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&32)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^32)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^32)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&16)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^16)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^16)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&8)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^8)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^8)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&4)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&2)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&1)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&128)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^255)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^255)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&64)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^64)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^64)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&32)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^32)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^32)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&16)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^16)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^16)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&8)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^8)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^8)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&4)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^4)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&2)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^2)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&1)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^1)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&256)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^511)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^511)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&128)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^128)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^128)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&64)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^64)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^64)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&32)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^32)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^32)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&16)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^16)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^16)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&8)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^8)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&4)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^4)]);
  __syncthreads();
  (( int *)(sbase + 2048))[tid] = ((tid&2)==0) ? min((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]) : max((( int *)sbase)[tid],(( int *)sbase)[(tid^2)]);
  __syncthreads();
  (( int *)sbase)[tid] = ((tid&1)==0) ? min((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]) : max((( int *)(sbase+2048))[tid],(( int *)(sbase+2048))[(tid^1)]);
  __syncthreads();
  result0[((bid*512)+tid)] = (( int *)sbase)[tid];
  
}
